name: yaru
version: 0.0.0-dev.1

description: Ubuntu Yaru theme

homepage: https://github.com/canonical/yaru.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
