name: yaru
version: 0.0.0-dev.4

description: Ubuntu Yaru theme

homepage: https://github.com/canonical/yaru.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/yaru/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: packages/yaru/fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/yaru/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: packages/yaru/fonts/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: packages/yaru/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: packages/yaru/fonts/Ubuntu-MI.ttf
          weight: 500
          style: italic
        - asset: packages/yaru/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: packages/yaru/fonts/Ubuntu-BI.ttf
          weight: 700
          style: italic
